In [841]:
import numpy as np
import pandas as pd
import seaborn as snp
import matplotlib.pyplot as plt

In [842]:
df=pd.read_csv("C:/Users/Qasim Saddique/Python_Jupyter/Project Naukri/Dataset_naukri.csv")
df.head(3)

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba

In [843]:
df.shape

(22000, 14)

In [844]:
df.columns

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id'],
      dtype='object')

In [845]:
count_missing=df.isnull().sum()
count_missing

company                    4
education               1996
experience                 4
industry                   5
jobdescription             4
jobid                      0
joblocation_address      501
jobtitle                   0
numberofpositions      17536
payrate                   97
postdate                  23
site_name              18013
skills                   528
uniq_id                    0
dtype: int64

In [846]:
len(df)

22000

In [847]:
percent_missing=(count_missing*100)/len(df)
percent_missing

company                 0.018182
education               9.072727
experience              0.018182
industry                0.022727
jobdescription          0.018182
jobid                   0.000000
joblocation_address     2.277273
jobtitle                0.000000
numberofpositions      79.709091
payrate                 0.440909
postdate                0.104545
site_name              81.877273
skills                  2.400000
uniq_id                 0.000000
dtype: float64

In [848]:
missing_value_df=pd.DataFrame({
    'Count_missing': count_missing,
    'Percent_missing': percent_missing
})

In [849]:
missing_value_df.style.background_gradient() # shades the cells based on their values using a gradient: Higher values get darker/brighter colors and Lower values get lighter colors

In [850]:
for col in df.columns:
    print(f"{col} has {df[col].nunique()} unique values") # .count() does not work here bcz df.unique returns a np array that does not have count fn or u can do: len(df[col].unique())

company has 8469 unique values
education has 2355 unique values
experience has 147 unique values
industry has 63 unique values
jobdescription has 21063 unique values
jobid has 21910 unique values
joblocation_address has 2329 unique values
jobtitle has 17564 unique values
numberofpositions has 84 unique values
payrate has 1848 unique values
postdate has 4203 unique values
site_name has 1 unique values
skills has 45 unique values
uniq_id has 22000 unique values

#### Now we will create a df that shows unique values and  "number of" unique values of a column correspoding to each column name

In [851]:
unique=[]
for col in df.columns:
    unique.append([col,df[col].nunique(),df[col].unique()])

# same using list comprehension
# unique=[ [col,df[col].nunique(), df[col].unique()] for col in df.columns]

In [852]:
data=pd.DataFrame(unique, columns=["Col Name","Count of Unique Values", "Unique Data"])
data

,Col Name,Count of Unique Values,Unique Data
0,company,8469,"[MM Media Pvt Ltd, find live infotech, Softtec..."
1,education,2355,[UG: B.Tech/B.E. - Any Specialization PG:Any P...
2,experience,147,"[0 - 1 yrs, 0 - 0 yrs, 4 - 8 yrs, 11 - 15 yrs,..."
3,industry,63,"[Media / Entertainment / Internet, Advertising..."
4,jobdescription,21063,[Job Description Send me Jobs like this Qual...
5,jobid,21910,"[210516002263, 210516002391, 101016900534, 810..."
6,joblocation_address,2329,"[Chennai, Bengaluru, Mumbai, Bengaluru, Kolkat..."
7,jobtitle,17564,"[Walkin Data Entry Operator (night Shift), Wor..."
8,numberofpositions,84,"[nan, 60.0, 4.0, 2.0, 20.0, 3.0, 1.0, 700.0, 8..."
9,payrate,1848,"[1,50,000 - 2,25,000 P.A, 1,50,000 - 2,50,000 ..."
10,postdate,4203,"[2016-05-21 19:30:00 +0000, 2016-10-13 16:20:5..."
11,site_name,1,"[nan, www.naukri.com]"
12,skills,45,"[ITES, Marketing, IT Software - Application Pr..."
13,uniq_id,22000,"[43b19632647068535437c774b6ca6cf8, d4c72325e57..."

In [853]:
data.style.background_gradient(cmap='Spectral') # shades the cells based on their values using a gradient

In [854]:
df['payrate'].head(20) # its min and max salary is separated by hyphen

0                               1,50,000 - 2,25,000 P.A
1                        1,50,000 - 2,50,000 P.A. 20000
2                            Not Disclosed by Recruiter
3                            Not Disclosed by Recruiter
4                            Not Disclosed by Recruiter
5                            Not Disclosed by Recruiter
6                               3,00,000 - 6,50,000 P.A
7                            Not Disclosed by Recruiter
8                               1,00,000 - 2,00,000 P.A
9                            Not Disclosed by Recruiter
10                           Not Disclosed by Recruiter
11                           Not Disclosed by Recruiter
12                              1,75,000 - 2,50,000 P.A
13                           Not Disclosed by Recruiter
14                           Not Disclosed by Recruiter
15                           Not Disclosed by Recruiter
16    1,00,000 - 2,00,000 P.A. incentives for achiev...
17                              1,00,000 - 5,00,000 P.A
18                           Not Disclosed by Recruiter
19                           Not Disclosed by Recruiter
Name: payrate, dtype: object

In [855]:
df['payrate'].dtype

dtype('O')

In [856]:
df['payrate'].apply(type).value_counts()

payrate
<class 'str'>      21903
<class 'float'>       97
Name: count, dtype: int64

In [857]:
df['payrate'][0].split("-")

['1,50,000 ', ' 2,25,000 P.A']

In [858]:
df['payrate'][0].split("-")[0]

'1,50,000 '

In [859]:
df['payrate'][0].split("-")[1]

' 2,25,000 P.A'

In [860]:
len_pay=[]
for pay in df['payrate']:
    len_pay.append(len(str(pay).split('-')))

In [861]:
pd.Series(len_pay).value_counts() # only entries of lenth 2 are valid entries

1    17028
2     4682
4      126
3       83
5       54
6       24
7        3
Name: count, dtype: int64

In [862]:
pay_split =df['payrate'].str.split('-', expand=True) # expand=True Return the result as separate columns in a DataFrame, instead of a list
pay_split

,0,1,2,3,4,5,6
0,"1,50,000","2,25,000 P.A",None,None,None,None,None
1,"1,50,000","2,50,000 P.A. 20000",None,None,None,None,None
2,Not Disclosed by Recruiter,None,None,None,None,None,None
3,Not Disclosed by Recruiter,None,None,None,None,None,None
4,Not Disclosed by Recruiter,None,None,None,None,None,None
...,...,...,...,...,...,...,...
21995,Not Disclosed by Recruiter,None,None,None,None,None,None
21996,"8,50,000","14,00,000 P.A",None,None,None,None,None
21997,Not Disclosed by Recruiter,None,None,None,None,None,None
21998,Not Disclosed by Recruiter,None,None,None,None,None,None
21999,"12,00,000","22,00,000 P.A",None,None,None,None,None

#### cleaning Minimum pay column

In [863]:
pay_split[0] # here 0 is the column name

0                         1,50,000
1                         1,50,000
2        Not Disclosed by Recruiter
3        Not Disclosed by Recruiter
4        Not Disclosed by Recruiter
                    ...
21995    Not Disclosed by Recruiter
21996                     8,50,000
21997    Not Disclosed by Recruiter
21998    Not Disclosed by Recruiter
21999                    12,00,000
Name: 0, Length: 22000, dtype: object

In [864]:
pay_split[0][0]

'1,50,000 '

In [865]:
pay_split[0]=pay_split[0].str.strip()

In [866]:
pay_split[0]

0                          1,50,000
1                          1,50,000
2        Not Disclosed by Recruiter
3        Not Disclosed by Recruiter
4        Not Disclosed by Recruiter
                    ...
21995    Not Disclosed by Recruiter
21996                      8,50,000
21997    Not Disclosed by Recruiter
21998    Not Disclosed by Recruiter
21999                     12,00,000
Name: 0, Length: 22000, dtype: object

In [867]:
pay_split[0] = pay_split[0].str.replace(',', '')

In [868]:
pay_split[0]= pay_split[0].str.extract(r'(\d+)')[0] # .str.extract() returns a DataFrame of groups.
                                                    #[0] selects the first (and only) column from that DataFrame.

In [869]:
pay_split[0] = pd.to_numeric(pay_split[0], errors='coerce') # If a value can't be converted to a number, replace it with NaN instead of raising an error

In [912]:
pay_split[0]

0         150000.0
1         150000.0
2              NaN
3              NaN
4              NaN
           ...
21995          NaN
21996     850000.0
21997          NaN
21998          NaN
21999    1200000.0
Name: 0, Length: 22000, dtype: float64

#### Cleaning Maximum pay column

In [871]:
pay_split[1]

0                2,25,000 P.A
1         2,50,000 P.A. 20000
2                        None
3                        None
4                        None
                 ...
21995                    None
21996           14,00,000 P.A
21997                    None
21998                    None
21999           22,00,000 P.A
Name: 1, Length: 22000, dtype: object

In [872]:
pay_split[1][0]

' 2,25,000 P.A'

In [873]:
pay_split[1]=pay_split[1].str.strip()

In [874]:
pay_split[1] = pay_split[1].astype(str).str.replace(',', '')

In [875]:
#pay_split[1] = pay_split[1].astype(str).str.replace(r'^(\d+).*', r'\1', regex=True) # ^(\d+) captures one or more digits at the beginning of the string.
# .* matches everything after that.
# The whole match (^(\d+).*) is replaced with only the captured digits (\1), effectively removing everything else in the string
 # \1 means: “replace the whole string with the first captured group”

In [876]:
pay_split[1] = pay_split[1].astype(str).str.replace(r'\D.*', '', regex=True)

In [877]:
pay_split[1]

0         225000
1         250000
2
3
4
          ...
21995
21996    1400000
21997
21998
21999    2200000
Name: 1, Length: 22000, dtype: object

In [878]:
pay_split[1]=pd.to_numeric(pay_split[1], errors='coerce')

In [879]:
pay_split[1]

0         225000.0
1         250000.0
2              NaN
3              NaN
4              NaN
           ...
21995          NaN
21996    1400000.0
21997          NaN
21998          NaN
21999    2200000.0
Name: 1, Length: 22000, dtype: float64

In [880]:
pay_split.dtypes

0    float64
1    float64
2     object
3     object
4     object
5     object
6     object
dtype: object

#### Concatenating Columns

In [881]:
# Easy way when you have less no. of cols to concat
#df['min_pay']=pay_split[0]
#df['max_pay']=pay_split[1]

In [882]:
#Another way, when you have more number of cols to add

pay_df= pd.concat([pay_split[0], pay_split[1]], axis=1)
pay_df.columns=['min_pay', 'max_pay']
pay_df

         min_pay    max_pay
0       150000.0   225000.0
1       150000.0   250000.0
2            NaN        NaN
3            NaN        NaN
4            NaN        NaN
...          ...        ...
21995        NaN        NaN
21996   850000.0  1400000.0
21997        NaN        NaN
21998        NaN        NaN
21999  1200000.0  2200000.0

[22000 rows x 2 columns]

In [883]:
df= pd.concat([df, pay_df], axis=1)

In [884]:
df.head()

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id,min_pay,max_pay
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8,150000.0,225000.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae,NaN,NaN
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4,NaN,NaN

### Cleaninig "Experience" column

In [885]:
df['experience']

0          0 - 1 yrs
1          0 - 0 yrs
2          4 - 8 yrs
3        11 - 15 yrs
4          6 - 8 yrs
            ...
21995     9 - 13 yrs
21996      3 - 5 yrs
21997      2 - 4 yrs
21998     7 - 12 yrs
21999     5 - 10 yrs
Name: experience, Length: 22000, dtype: object

In [886]:
split_df=df['experience'].str.split('-', expand=True)

In [887]:
split_df # It means there are more than 1 hyphens in some rows

         0        1     2
0       0     1 yrs  None
1       0     0 yrs  None
2       4     8 yrs  None
3      11    15 yrs  None
4       6     8 yrs  None
...    ...      ...   ...
21995   9    13 yrs  None
21996   3     5 yrs  None
21997   2     4 yrs  None
21998   7    12 yrs  None
21999   5    10 yrs  None

[22000 rows x 3 columns]

#### solution

In [888]:
df[ df['experience'].str.count('-') > 1 ]

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id,min_pay,max_pay
12906,National Institute of Industrial Engineering,NaN,3 - -1 yrs,Education / Teaching / Training,Job Description Send me Jobs like this Facul...,170516902039,Mumbai,Assistant Professor - System Dynamics Modeling,NaN,Pay Scale: PB-3 (Rs.I5600-39100) with AGP of R...,2016-05-17 19:48:50 +0000,www.naukri.com,Teaching,41775d36e684d01712fb06a7f7dfc16c,NaN,3.0

In [889]:
# or
df['experience'].str.count('-').value_counts()

experience
1.0    21884
0.0      111
2.0        1
Name: count, dtype: int64

In [890]:
df['experience'] = df['experience'].astype(str).str.replace(' - -', ' - ')

In [891]:
split_df=df['experience'].str.split('-', expand=True)
split_df

         0        1
0       0     1 yrs
1       0     0 yrs
2       4     8 yrs
3      11    15 yrs
4       6     8 yrs
...    ...      ...
21995   9    13 yrs
21996   3     5 yrs
21997   2     4 yrs
21998   7    12 yrs
21999   5    10 yrs

[22000 rows x 2 columns]

In [892]:
split_df.columns=['min_exp', 'max_exp']

In [893]:
df=pd.concat([df,split_df], axis=1)
df

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id,min_pay,max_pay,min_exp,max_exp
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0,1 yrs
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0,0 yrs
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4,8 yrs
3,Onboard HRServices LLP,UG: Any Graduate - Any Specialization PG:CA Do...,11 - 15 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this - Inv...,81016900536,"Mumbai, Bengaluru, Kolkata, Chennai, Coimbator...",Manager/ad/partner - Indirect Tax - CA,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,Accounts,115d28f140f694dd1cc61c53d03c66ae,NaN,NaN,11,15 yrs
4,Spire Technologies and Solutions Pvt. Ltd.,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,6 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Pleas...,120916002122,Bengaluru,JAVA Technical Lead (6-8 yrs) -,4.0,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,a12553fc03bc7bcced8b1bb8963f97b4,NaN,NaN,6,8 yrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,Morgan Stanley Advantage Services Pvt. Ltd.,UG: Any Graduate - Any Specialization,9 - 13 yrs,Banking / Financial Services / Broking,Job Description Send me Jobs like this Greet...,241116007152,Bengaluru,Quality Assurance - VP with Morgan Stanley Ban...,2.0,Not Disclosed by Recruiter,2016-11-25 22:47:05 +0000,www.naukri.com,IT Software - QA & Testing,ef40136e3b0c0abdab695d979a4b7153,NaN,NaN,9,13 yrs
21996,Careernet Technologies Pvt Ltd hiring for Client,UG: B.Tech/B.E. - Any Specialization PG:M.Tech...,3 - 5 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Looki...,241116001104,"Bengaluru, Gurgaon",Java Backend Developers for a Product Company,NaN,"8,50,000 - 14,00,000 P.A",2016-11-24 22:47:05 +0000,www.naukri.com,IT Software - Application Programming,acb80b7bb109fa76d22d1f11c6e16c6a,850000.0,1400000.0,3,5 yrs
21997,Musk - Startup,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,2 - 4 yrs,Internet / Ecommerce,Job Description Send me Jobs like this Work ...,251116900644,Bengaluru,Full Stack Development Engineer,NaN,Not Disclosed by Recruiter,2016-11-25 22:47:05 +0000,www.naukri.com,IT Software - Application Programming,f6f2885a6c87572616fb766029a0d284,NaN,NaN,2,4 yrs
21998,Confidential,UG: B.Tech/B.E. - Any Specialization PG:MCA - ...,7 - 12 yrs,IT-Software / Software Services,Job Description Send me Jobs like this We ar...,231116901329,"Delhi NCR, Bengaluru",Sr UI Developer/ Technical Lead - Html/ CSS/ J...,NaN,Not Disclosed by Recruiter,2016-11-27 22:47:05 +0000,www.naukri.com,IT Software - Application Programming,c6f6538cb1007dd02c1b4b77909b3d38,NaN,NaN,7,12 yrs
21999,Cambio Consulting India Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:MCA - ...,5 - 10 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Job d...,251116003840,Bengaluru,RF Firmware Engineers,NaN,"12,00,000 - 22,00,000 P.A",2016-11-25 22:47:05 +0000,www.naukri.com,IT Software - System Programming,74fec26df6e1c0be0171311a2f03f180,1200000.0,2200000.0,5,10 yrs

In [894]:
df['max_exp']=df['max_exp'].str.replace('yrs', '').str.strip()
df['min_exp'] = df['min_exp'].replace('Not Mentioned', np.nan)

In [895]:
df['min_exp'] = df['min_exp'].replace('', np.nan)
df['min_exp']= df['min_exp'].astype(float)

In [896]:
df['max_exp']= df['max_exp'].astype(float)

In [897]:
df['avg_pay']= (df['min_pay']+df['max_pay'])/2

In [898]:
df['avg_exp']= (df['min_exp']+df['max_exp'])/2

In [899]:
df.head(3)

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,postdate,site_name,skills,uniq_id,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",2016-05-21 19:30:00 +0000,NaN,ITES,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0.0,1.0,187500.0,0.5
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",2016-05-21 19:30:00 +0000,NaN,Marketing,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0.0,0.0,200000.0,0.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,2016-10-13 16:20:55 +0000,NaN,IT Software - Application Programming,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4.0,8.0,NaN,6.0

In [900]:
df.dtypes

company                 object
education               object
experience              object
industry                object
jobdescription          object
jobid                    int64
joblocation_address     object
jobtitle                object
numberofpositions      float64
payrate                 object
postdate                object
site_name               object
skills                  object
uniq_id                 object
min_pay                float64
max_pay                float64
min_exp                float64
max_exp                float64
avg_pay                float64
avg_exp                float64
dtype: object

#### Cleaning Post Date Column

In [901]:
df['postdate'].dtype

dtype('O')

In [902]:
df['postdate']=pd.to_datetime(df['postdate'])

In [903]:
df['day'] = df['postdate'].dt.day
df['month'] = df['postdate'].dt.month
df['year'] = df['postdate'].dt.year
df.head(3)

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,...,uniq_id,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp,day,month,year
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,0 - 1 yrs,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,"1,50,000 - 2,25,000 P.A",...,43b19632647068535437c774b6ca6cf8,150000.0,225000.0,0.0,1.0,187500.0,0.5,21.0,5.0,2016.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,0 - 0 yrs,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,"1,50,000 - 2,50,000 P.A. 20000",...,d4c72325e57f89f364812b5ed5a795f0,150000.0,250000.0,0.0,0.0,200000.0,0.0,21.0,5.0,2016.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,4 - 8 yrs,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,Not Disclosed by Recruiter,...,c47df6f4cfdf5b46f1fd713ba61b9eba,NaN,NaN,4.0,8.0,NaN,6.0,13.0,10.0,2016.0

#### Filtering

In [904]:
df['joblocation_address']=='Noida'

0        False
1        False
2        False
3        False
4        False
         ...
21995    False
21996    False
21997    False
21998    False
21999    False
Name: joblocation_address, Length: 22000, dtype: bool

In [905]:
loc_noida = df[ df['joblocation_address']=='Noida' ]

In [906]:
loc_noida

,company,education,experience,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,payrate,...,uniq_id,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp,day,month,year
1756,Aristocrat Technologies India Pvt. ltd.,UG: B.Tech/B.E. PG:Post Graduation Not Require...,5 - 7 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Test ...,240516500179,Noida,Senior Engineer- Testing,NaN,Not Disclosed by Recruiter,...,05e7588ceed77b2ba2ff543131511dc0,NaN,NaN,5.0,7.0,NaN,6.0,24.0,5.0,2016.0
1757,Reliant HR Management Sevice Pvt Ltd,"UG: Any Graduate PG:MBA/PGDM, Any Postgraduate...",7 - 10 yrs,Strategy / Management Consulting Firms,Job Description Send me Jobs like this We ar...,240516500333,Noida,Branch Accountant,NaN,Not Disclosed by Recruiter,...,67b9bb431f0b7a415892e7ef3d2c591a,NaN,NaN,7.0,10.0,NaN,8.5,24.0,5.0,2016.0
1760,Ebix Software India Pvt. Ltd,UG: Any Graduate PG:Any Postgraduate Doctorate...,8 - 10 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Prima...,200516500544,Noida,Senior Graphic Designer/ ISD,NaN,Not Disclosed by Recruiter,...,9e10d19a04fae291a383dfc94d2e92d5,NaN,NaN,8.0,10.0,NaN,9.0,20.0,5.0,2016.0
1778,Valuecons Services,"UG: BCA - Computers, B.Tech/B.E. - Electrical ...",3 - 5 yrs,Strategy / Management Consulting Firms,Job Description Send me Jobs like this Urgen...,290516600284,Noida,Urgent Job Opening for iOS Developer @ Noida L...,NaN,Not Disclosed by Recruiter,...,ce3b3606f6bec9383218138ca4e2369f,NaN,NaN,3.0,5.0,NaN,4.0,28.0,5.0,2016.0
1782,Mindworks Global Media Services,UG: Any Graduate PG:Post Graduation Not Requir...,5 - 7 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Job d...,250516500085,Noida,Client Servicing/ Account Manager,NaN,Not Disclosed by Recruiter,...,f01cbefb8008c5d58a1ce834aab6e95a,NaN,NaN,5.0,7.0,NaN,6.0,25.0,5.0,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20150,Corbus India Pvt. Ltd.,UG: Any Graduate PG:Post Graduation Not Requir...,1 - 3 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Analy...,160315500051,Noida,Associate - Supply Chain Management,NaN,Not Disclosed by Recruiter,...,b24945bfbd43a43d6b9d91b15c54d0af,NaN,NaN,1.0,3.0,NaN,2.0,22.0,11.0,2015.0
20166,Fashion Design Council of India,UG: Any Graduate PG:Post Graduation Not Requir...,1 - 2 yrs,Textiles / Garments / Accessories,Job Description Send me Jobs like this Job D...,170715502663,Noida,Assistant Designer,NaN,Not Disclosed by Recruiter,...,8d40014ac2e762834aa8f2cd5654ecc6,NaN,NaN,1.0,2.0,NaN,1.5,22.0,11.0,2015.0
20169,Quest Venture Coordinators Pvt. Ltd,UG: Any Graduate PG:Post Graduation Not Requir...,0 - 2 yrs,BPO / Call Centre / ITES,Job Description Send me Jobs like this Data ...,170715502754,Noida,DATA ENTRY,NaN,Not Disclosed by Recruiter,...,a943f4156883762deda92db042e24ea6,NaN,NaN,0.0,2.0,NaN,1.0,22.0,11.0,2015.0
20171,ImpactQA,UG: B.Tech/B.E. PG:MCA Doctorate:Any Doctorate...,4 - 6 yrs,IT-Software / Software Services,Job Description Send me Jobs like this Requi...,170715502521,Noida,QA Lead,NaN,Not Disclosed by Recruiter,...,fdeb2f3a9046bf9fd47be864f6b863a8,NaN,NaN,4.0,6.0,NaN,5.0,22.0,11.0,2015.0
20182,Pathways World School.,UG: B.Tech/B.E. PG:M.Tech Doctorate:Any Doctor...,5 - 10 yrs,Education / Teaching / Training,Job Description Send me Jobs like this Job D...,160715501418,Noida,Head of Science Department,NaN,Not Disclosed by Recruiter,...,20bfc515e3249e8dc098b80488d350b3,NaN,NaN,5.0,10.0,NaN,7.5,22.0,11.0,2015.0

In [907]:
df.columns # Now we have many useless cols, we should drop them

Index(['company', 'education', 'experience', 'industry', 'jobdescription',
       'jobid', 'joblocation_address', 'jobtitle', 'numberofpositions',
       'payrate', 'postdate', 'site_name', 'skills', 'uniq_id', 'min_pay',
       'max_pay', 'min_exp', 'max_exp', 'avg_pay', 'avg_exp', 'day', 'month',
       'year'],
      dtype='object')

In [908]:
def drop_features(cols):
    df.drop(cols, axis=1, inplace=True)

In [909]:
drop_features(['experience','payrate','postdate','uniq_id'])

In [910]:
df.head(3)

,company,education,industry,jobdescription,jobid,joblocation_address,jobtitle,numberofpositions,site_name,skills,min_pay,max_pay,min_exp,max_exp,avg_pay,avg_exp,day,month,year
0,MM Media Pvt Ltd,UG: B.Tech/B.E. - Any Specialization PG:Any Po...,Media / Entertainment / Internet,Job Description Send me Jobs like this Quali...,210516002263,Chennai,Walkin Data Entry Operator (night Shift),NaN,NaN,ITES,150000.0,225000.0,0.0,1.0,187500.0,0.5,21.0,5.0,2016.0
1,find live infotech,UG: B.Tech/B.E. - Any Specialization PG:MBA/PG...,Advertising / PR / MR / Event Management,Job Description Send me Jobs like this Quali...,210516002391,Chennai,Work Based Onhome Based Part Time.,60.0,NaN,Marketing,150000.0,250000.0,0.0,0.0,200000.0,0.0,21.0,5.0,2016.0
2,Softtech Career Infosystem Pvt. Ltd,UG: Any Graduate - Any Specialization PG:Any P...,IT-Software / Software Services,Job Description Send me Jobs like this - as ...,101016900534,Bengaluru,Pl/sql Developer - SQL,NaN,NaN,IT Software - Application Programming,NaN,NaN,4.0,8.0,NaN,6.0,13.0,10.0,2016.0

In [911]:
df.to_csv('cleaned_data.csv', index=False)